export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 1",
    type: "new",
    priority: "high",
  },
  {
    id: 2,
    title: "Task 2",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 2",
    type: "new",
    priority: "high",
  },
  {
    id: 3,
    title: "Task 3",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 3",
    type: "new",
    priority: "high",
  },
  {
    id: 4,
    title: "Task 4",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 4",
    type: "new",
    priority: "high",
  },
  {
    id: 5,
    title: "Task 5",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 5",
    type: "new",
    priority: "high",
  },
  {
    id: 6,
    title: "Task 6",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Cristina Shim",
    description: "Desc 6",
    type: "new",
    priority: "high",
  },
];
